_BASE_: [
  '../yolox/yolox_s_300e_coco.yml',
  '../datasets/voc.yml',
]
log_iter: 50
snapshot_epoch: 5
weights: output/yolox_s_40e_voc/model_final

pretrain_weights: https://paddledet.bj.bcebos.com/models/yolox_s_300e_coco.pdparams
depth_mult: 0.33
width_mult: 0.50

TrainReader:
  batch_size: 8 # default 8 gpus, total bs = 64

EvalReader:
  batch_size: 4


epoch: 40
LearningRate:
  base_lr: 0.001
  schedulers:
  - !CosineDecay
    max_epochs: 40
    min_lr_ratio: 0.05
    last_plateau_epochs: 4
  - !ExpWarmup
    epochs: 1
