_BASE_: [
  '../yolov5/yolov5_s_300e_coco.yml',
  '../datasets/voc.yml',
]
log_iter: 50
snapshot_epoch: 5
weights: output/yolov5_s_60e_voc/model_final

pretrain_weights: https://paddledet.bj.bcebos.com/models/yolov5_s_300e_coco.pdparams
depth_mult: 0.33
width_mult: 0.50


TrainReader:
  batch_size: 16 # default 8 gpus, total bs = 128

EvalReader:
  batch_size: 4


epoch: 60
LearningRate:
  base_lr: 0.001
  schedulers:
  - !YOLOv5LRDecay
    max_epochs: 60
    min_lr_ratio: 0.01
  - !ExpWarmup
    epochs: 1
