_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_500e.yml',
  '_base_/yolov10_cspdarknet.yml',
  '_base_/yolov10_reader.yml',
]
depth_mult: 1.00
width_mult: 1.25

log_iter: 50
snapshot_epoch: 10
weights: output/yolov10_x_500e_coco/model_final

YOLOv10CSPDarkNet:
  arch: 'X'
  last_stage_ch: 512
  use_c2fcib: true
  use_large_kernel: false

YOLOv10CSPPAN:
  fpn_use_c2fcib: [true, false]
  pan_use_c2fcib: [true, true]
  use_large_kernel: false
