_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_500e.yml',
  '_base_/yolov8_cspdarknet.yml',
  '_base_/yolov8_reader.yml',
]
depth_mult: 0.33
width_mult: 0.25

log_iter: 10
snapshot_epoch: 1
weights: output/0


TrainReader:
  batch_size: 64 # default 8 gpus, total bs = 128
